In [1]:
import pandas as pd

In [2]:
path_to_file ='2_bookings.csv'

In [4]:
df=pd.read_csv(path_to_file,sep=';')

In [8]:
df.head(7)

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03

In [9]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [10]:
df

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

In [19]:
top5=df[df['is_canceled']==0]['country'].value_counts().head(5)

In [20]:
top5

country
PRT    21071
GBR     9676
FRA     8481
ESP     6391
DEU     6069
Name: count, dtype: int64

In [23]:
df.groupby('hotel').stays_total_nights.mean()

hotel
City Hotel      2.978142
Resort Hotel    4.318547
Name: stays_total_nights, dtype: float64

In [27]:
(df['assigned_room_type']!=df['reserved_room_type']).sum()

np.int64(14917)

In [31]:
df[df['assigned_room_type'] != df['reserved_room_type']].groupby('hotel').size()

hotel
City Hotel      7192
Resort Hotel    7725
dtype: int64

In [42]:
succ=df[df['is_canceled']==0]

In [43]:
succ

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

In [54]:
pop2016=succ[succ['arrival_date_year']==2016]['arrival_date_month'].value_counts().idxmax()

In [55]:
pop2016

'October'

In [56]:
pop2017=succ[succ['arrival_date_year']==2017]['arrival_date_month'].value_counts().idxmax()

In [57]:
pop2017

'May'

In [62]:
canceled=df[df['is_canceled']==1].groupby('arrival_date_year')

In [64]:
canceled = df[(df['is_canceled'] == 1) & (df['hotel'] == 'City Hotel')]

In [65]:
canceled

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
40061,City Hotel,1,88,2015-07-01,2015,July,27,1,0,4,...,2,0.0,0,BB,PRT,A,A,Transient,Canceled,2015-07-01
40062,City Hotel,1,65,2015-07-01,2015,July,27,1,0,4,...,1,0.0,0,BB,PRT,A,A,Transient,Canceled,2015-04-30
40063,City Hotel,1,92,2015-07-01,2015,July,27,1,2,4,...,2,0.0,0,BB,PRT,A,A,Transient,Canceled,2015-06-23
40064,City Hotel,1,100,2015-07-02,2015,July,27,2,0,2,...,2,0.0,0,BB,PRT,A,A,Transient,Canceled,2015-04-02
40065,City Hotel,1,79,2015-07-02,2015,July,27,2,0,3,...,2,0.0,0,BB,PRT,A,A,Transient,Canceled,2015-06-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110280,City Hotel,1,132,2017-04-25,2017,April,17,25,0,0,...,0,0.0,0,BB,FRA,D,K,Transient,Canceled,2017-04-25
111355,City Hotel,1,4,2017-06-05,2017,June,23,5,1,0,...,1,0.0,0,BB,PRT,A,A,Transient,Canceled,2017-06-05
111924,City Hotel,1,7,2017-05-31,2017,May,22,31,0,1,...,1,0.0,0,BB,PRT,A,A,Transient,Canceled,2017-05-31
111925,City Hotel,1,6,2017-07-17,2017,July,29,17,1,0,...,1,0.0,0,BB,PRT,A,D,Transient,No-Show,2017-07-17
117295,City Hotel,1,0,2017-08-02,2017,August,31,2,0,2,...,1,0.0,0,BB,PRT,A,C,Transient,No-Show,2017-08-02

In [72]:
canceled = df[(df['is_canceled'] == 1) & (df['hotel'] == 'City Hotel')].groupby('arrival_date_year')['arrival_date_month'].agg(lambda x: x.value_counts().idxmax())

In [73]:
canceled

arrival_date_year
2015    September
2016      October
2017          May
Name: arrival_date_month, dtype: object

In [79]:
df[['adults','children','babies']].mean()

adults      1.856403
children    0.103890
babies      0.007949
dtype: float64

In [84]:
df['total_kids']=df['children']+df['babies']

In [89]:
df.groupby('hotel')['total_kids'].mean().idxmax()

'Resort Hotel'

In [ ]:
df['total_kids']>0['has_kids']==1